name: build

on: push

env:
  DOTNET_NOLOGO: 1 # Disable the .NET welcome message
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 # Opt out of the .NET SDK telemetry feature

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            dotnet-version: 5.0.103

          - os: ubuntu-latest
            dotnet-version: 5.0.103

          - os: windows-latest
            dotnet-version: 5.0.201

          - os: ubuntu-latest
            dotnet-version: 5.0.201
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET 5 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Build
      run: dotnet build --configuration Release --verbosity minimal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet packages for ${{ matrix.os }} dotnet-version ${{ matrix.dotnet-version }}
        path: artifacts/*.nupkg
